### ISSUE TITLE
I made a version of tree.c in OpenJSCAD, if you want to link to it feel free

### ISSUE THREAD

**Issue by aklef** [smcameron/opencscad#1]
Hi! I enjoyed your work so much I decided to try port it to OpenJSCAD. (spoiler: your version was better)

You're welcome to delete this issue or link to my repo as you wish!

https://github.com/aklef/OpenJSCAD-Tree-demo

Just wanted to say hi, thank you and give you a head's up

**Comment by smcameron** [comment]
Thanks.  I wrote that many years ago before openscad supported recursion.  Now it does, and in fact, in the manual, they use a tree as an example of a recursive module: 


https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#Recursive_Modules

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#/media/File:Simple_recursive_tree.png
